### ISSUE TITLE
error installing KAML

### ISSUE THREAD

**Issue by sosolero** [YinLiLin/KAML#1]
devtools::install_github("YinLiLin/R-KAML/KAML")

from URL https://api.github.com/repos/YinLiLin/R-KAML/zipball/master
Installation failed: Does not appear to be an R package (no DESCRIPTION)

**Comment by YinLiLin** [comment]
Hi, 

The project of KAML is ongoing, and we are optimizing it to more stable and accurate, this may need some time. If we update the final version, i will inform you immediately!

Thanks
