### ISSUE TITLE
Question: Heritability estimation?

### ISSUE THREAD

**Issue by jguhlin** [YinLiLin/KAML#13]
Is there a straight-forward way to get a heritability estimation from KAML / quantify the variance explained by the predicted values?

**Comment by YinLiLin** [comment]
Sorry, the current version does not return the variance components, i will achieve this function in the coming days, and once finished, i will feed back here. Thanks.

**Comment by jguhlin** [comment]
That'd be great, thanks!

**Comment by YinLiLin** [comment]
The latest version (v1.3.0) of KAML on GitHub has been updated for obtaining the variance components (named as "vg", "ve"), please try again.

**Comment by YinLiLin** [comment]
The latest version (v1.3.0) of KAML on GitHub has been updated for obtaining the variance components (named as "vg", "ve"), please try again.

**Comment by jguhlin** [comment]
Thanks for the quick addition, it really helps! I noticed K.method was removed, can you tell me which method is being used now? I was previously using vanraden for best results.

I've got a very small population which is very sensitive to the parameters, which is why I ask. I've been using hibayes as well (although the bayesr implementation seems to fail on small pops, but I need to do some more digging)

**Comment by YinLiLin** [comment]
Yes, the parameter "K.method" has been removed in the latest version, from our testing, there is no significant difference on the predictive performance for the Kinship calculated by different algorithms. The "vanraden" method is the default in the latest version.
Also thank you for using hibayes, if you encounter any problem, welcome to submit an issue in the repository of hibayes.

**Comment by jguhlin** [comment]
Ah, that's good to know. Thank you. I'll submit an issue to hibayes repo when I've narrowed the problem down a bit more. Cheers
