### ISSUE TITLE
Microsoft R Open end of life

### ISSUE THREAD

**Issue by m-hrachov** [YinLiLin/KAML#17]
MRO will not be supported from the next month. And already now I cannot download packages to an installation of MRO 4.0.2 I have on my PC. Have you maybe made a re-pack or know a walkaround to use? I would highly appreciate any advice.

**Comment by hyacz** [comment]
MRO has retired on July 1, 2022, and MRAN will stop serving next month. If you want to continue using MRO, you can switch the mirror to the default CRAN. For more information see [What’s happening to Microsoft R Application Network?](https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161)

I tested that MRO can still be installed normally, or you can try to install MRO from conda, and KAML is a package hosted on CRAN and Github, which will not be affected by the end of life of MRO & MRAN.

**Comment by m-hrachov** [comment]
Thank you for a comment on this issue.

For those who come here later, the right way to solve the problem is:

``` r
options('repos') # to see the current repository
file.path(R.home(), ".Rprofile")
```
go to the file and change `r["CRAN"] <- RevoUtils::getRevoRepos()` to r["CRAN"] <- "https://cloud.r-project.org/"
Run R again. In WSL Ubuntu the permission can be denied unless opened as the `./sudo nano Rprofile.site`.

Run R and check the repo again `options('repos')`.
